window.SUSHINI_FORTUNES = [
  "La calma abre puertas que la prisa no puede ver.",
  "Un gesto amable volverá a ti cuando menos lo esperes.",
  "Hoy es buen día para confiar en tu intuición.",
  "La paciencia convierte pequeños pasos en grandes caminos.",
  "Una noticia agradable llegará por una conversación sencilla.",
  "Tu esfuerzo silencioso pronto tendrá una recompensa visible.",
  "La fortuna sonríe a quien cuida los detalles.",
  "El equilibrio que buscas comienza con una pausa.",
  "Una amistad sincera será luz en una decisión importante.",
  "El mejor momento para empezar es el que tienes enfrente.",
  "La gratitud hará más dulce lo que ya tienes.",
  "Una oportunidad pequeña puede traer un cambio grande.",
  "Tu creatividad encontrará una salida inesperada.",
  "Lo que hoy preparas con cariño mañana dará fruto.",
  "Escucha con atención: ahí viene una respuesta.",
  "La suerte camina junto a las personas constantes.",
  "Un nuevo aprendizaje te acercará a lo que deseas.",
  "Tu serenidad será tu mejor herramienta esta semana.",
  "Un detalle sencillo alegrará el corazón de alguien.",
  "El orden en tus ideas traerá paz a tus días.",
  "Una invitación inesperada abrirá una buena historia.",
  "La alegría también se encuentra en las cosas pequeñas.",
  "Tu generosidad dejará una huella duradera.",
  "Una meta pendiente comenzará a moverse a tu favor.",
  "Confía en el proceso: estás más cerca de lo que piensas.",
  "La claridad llegará después de descansar la mente.",
  "Un sí valiente cambiará el tono de tu semana.",
  "El cuidado que das regresará multiplicado.",
  "Una conversación honesta limpiará el camino.",
  "La fortuna visita a quien se prepara con cariño.",
  "Tu presencia tranquila será un regalo para otros.",
  "Lo simple será la respuesta más elegante.",
  "Un recuerdo bonito te recordará hacia dónde ir.",
  "La abundancia comienza cuando reconoces lo suficiente.",
  "Tu corazón sabe distinguir lo verdadero.",
  "Una puerta se abrirá cuando dejes de empujar la equivocada.",
  "El día traerá una señal pequeña pero clara.",
  "La disciplina de hoy será libertad mañana.",
  "Tu sonrisa será parte de una buena noticia.",
  "Un cambio de ritmo te devolverá energía.",
  "La buena fortuna ama las manos trabajadoras.",
  "Recibirás apoyo de donde no lo esperabas.",
  "Un sueño antiguo merece una nueva oportunidad.",
  "La belleza aparecerá en una rutina conocida.",
  "Tu paciencia será recompensada con claridad.",
  "Algo que parecía lento está tomando forma.",
  "La paz se construye con decisiones pequeñas.",
  "Una idea compartida crecerá más de lo imaginado.",
  "La confianza será el ingrediente que faltaba.",
  "No subestimes el poder de hacer una cosa bien.",
  "Tu camino se ilumina cuando eliges con calma.",
  "Una sorpresa dulce llegará al final del día.",
  "Las buenas noticias prefieren los corazones atentos.",
  "El respeto por tu tiempo atraerá mejores planes.",
  "Una pausa a tiempo evitará una preocupación innecesaria.",
  "La fortuna entra por la puerta de la gratitud.",
  "Tu amabilidad será recordada más de lo que imaginas.",
  "Un inicio pequeño tendrá un resultado hermoso.",
  "La respuesta vendrá cuando mires desde otro ángulo.",
  "Tu esfuerzo está sembrando raíces profundas.",
  "Una elección sencilla te acercará a la armonía.",
  "La vida te ofrecerá una razón para celebrar.",
  "Lo que haces con amor encuentra buen destino.",
  "Una persona cercana traerá una idea valiosa.",
  "Tu constancia convertirá la duda en confianza.",
  "El buen gusto también es una forma de cuidado.",
  "Un mensaje inesperado traerá tranquilidad.",
  "La suerte favorece a quien mantiene el corazón abierto.",
  "Una pequeña mejora cambiará toda la experiencia.",
  "La calma será tu manera de avanzar más rápido.",
  "Tu talento brillará en un momento cotidiano.",
  "Una decisión pendiente encontrará su mejor momento.",
  "El día será más amable si empiezas despacio.",
  "La prosperidad crece donde hay intención limpia.",
  "Un detalle de cariño transformará el ambiente.",
  "Tu intuición reconocerá una buena oportunidad.",
  "La armonía llegará cuando sueltes lo que pesa.",
  "Un logro discreto merece ser celebrado.",
  "La suerte también se cocina con paciencia.",
  "Tu energía atraerá conversaciones positivas.",
  "Una respuesta sencilla resolverá algo complicado.",
  "El futuro se vuelve claro cuando honras el presente.",
  "La bondad que compartes abrirá caminos suaves.",
  "Un encuentro breve dejará una alegría larga.",
  "Tu tranquilidad inspirará confianza en otros.",
  "La fortuna reconoce a quien no deja de intentar.",
  "Una nueva rutina traerá buenos resultados.",
  "El amor por los detalles hará especial este día.",
  "Tu voz será necesaria en una conversación importante.",
  "Lo que parecía perdido puede regresar renovado.",
  "Una señal de avance llegará antes de lo esperado.",
  "La claridad nace cuando escuchas sin miedo.",
  "Tu mejor respuesta será actuar con elegancia.",
  "Una buena noticia merece compartirse con calma.",
  "La suerte se acerca cuando haces espacio para ella.",
  "Tu dedicación convertirá lo ordinario en memorable.",
  "Un pequeño acto de valentía abrirá una etapa nueva.",
  "El bienestar empieza con tratarte con ternura.",
  "La confianza crece cuando cumples contigo.",
  "Un plan sencillo tendrá un resultado delicioso.",
  "Tu mirada atenta descubrirá una ventaja oculta.",
  "La vida premiará tu manera de cuidar.",
  "Una oportunidad llegará vestida de tarea pequeña.",
  "La paz interior será tu brújula más fiel.",
  "Tu alegría encontrará una forma de multiplicarse.",
  "Un cambio amable renovará tu motivación.",
  "La prosperidad te encuentra cuando actúas con propósito.",
  "Una conversación pendiente terminará mejor de lo esperado.",
  "Tu constancia será más fuerte que cualquier duda.",
  "El universo te guiña el ojo en los detalles.",
  "Una elección consciente traerá descanso al corazón.",
  "La fortuna no grita; susurra en el momento correcto.",
  "Tu buen ánimo abrirá una puerta inesperada.",
  "Un deseo bien cuidado comenzará a tomar forma.",
  "La abundancia llegará en una forma tranquila.",
  "Hoy tendrás una razón para agradecer dos veces."
];
